"""Add contact_information column to post table

Revision ID: 904d9a86e071
Revises: fd34abebd22c
Create Date: 2025-03-08 10:54:25.074750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904d9a86e071'
down_revision = 'fd34abebd22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maximum_temperature', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('maximum_humidity', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('maximum_humidity')
        batch_op.drop_column('maximum_temperature')

    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('food_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
