"""Add food form model

Revision ID: fd34abebd22c
Revises: 0671e6010017
Create Date: 2025-03-05 17:06:59.735595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd34abebd22c'
down_revision = '0671e6010017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('batch_number', sa.String(length=100), nullable=False))
        batch_op.drop_column('food_name')
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('food_name', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('batch_number')
        batch_op.drop_column('food_name')

    # ### end Alembic commands ###
